---

- hosts: localhost
  roles:
    - { role: apps, tags: ["apps"] }
    - { role: docker, tags: ["ci"] }
    - { role: git_config, tags: ["ci"] }
    - { role: php, tags: ["dev"] }
    - { role: "geerlingguy.composer", tags: "composer" }
