---

- name: Installing Common Apt packages
  become: yes
  become_method: sudo
  apt:
    pkg:
    - vim
    - tmux
    - htop
    - jq
    - gdebi
    - gulp
    - npm

- name: Install snaps
  become: yes
  become_method: sudo
  community.general.snap:
    name: authy
    channel: beta
    name: mysql-workbench-community

