---

- name: Installing PHP Apt packages
  become: yes
  become_method: sudo
  apt:
    pkg:
      - php7.4
      - curl
      - php7.4-cli
      - php7.4-mbstring
      - unzip
      - php7.4-curl
      - php7.4-dom
      - php7.4-zip
